version: '3.7'
services:
  app:
    build: .
    command: yarn start
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - db
    ports:
      - 3000:3000
    restart: always

  db:
    image: mongo:4.4.0-bionic
    volumes:
      - db-data:/data/db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MONGO_INITDB_DATABASE: ${DATABASE_NAME}

volumes:
  db-data:
